name: Build and Deploy Docs
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    strategy:
      fail-fast: true
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run docs:build
      - run: cp -vr /home/runner/work/craft-vite/craft-vite/docs/docs/.vitepress/dist ${{ github.workspace }}
      - run: ls -al /home/runner/work/craft-vite/craft-vite/docs/docs/.vitepress/dist
      - run: ls -al ${{ github.workspace }}
      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: ./dist
          remote_path: ${{ secrets.NYS_DOCS_ROOT }}/vite
          remote_host: ${{ secrets.NYS_DEPLOY_REMOTE_HOST }}
          remote_port: ${{ secrets.NYS_DEPLOY_REMOTE_PORT }}
          remote_user: ${{ secrets.NYS_DEPLOY_REMOTE_USER }}
          remote_key: ${{ secrets.NYS_DEPLOY_PRIVATE_KEY }}
